### ISSUE TITLE
The web ran on blank page

### ISSUE THREAD

**Issue by thanhhiepvo** [Devaansh-Kumar/TalkToMe#9]
I cloned the repos.
I installed the npm
I updated the Browserslist BD (the lastest version)
I updated the Chrome (lastest version)

But .... The web ran on localhost showed the blank page

I did all the steps
![Screenshot 2024-02-01 172926](https://github.com/Devaansh-Kumar/TalkToMe/assets/88677902/849247fd-2fd5-4bb2-ab23-96c3bc527612)

The web is blank page
![Screenshot (259)](https://github.com/Devaansh-Kumar/TalkToMe/assets/88677902/abcdd9ac-6c0e-4425-9946-96e95fd29130)

**Comment by Devaansh-Kumar** [comment]
Could you send a screen shot of the console on the browser

**Comment by thanhhiepvo** [comment]
Of course. I edited the issue above

**Comment by Devaansh-Kumar** [comment]
I meant press Ctrl+Shift+C on the browser and send the logs of that console. Mostly the issue is because you dont have environment variables that is required in this file: https://github.com/Devaansh-Kumar/TalkToMe/blob/main/src/firebase.js

**Comment by thanhhiepvo** [comment]
You was right. I have problem with firebase

![Screenshot 2024-02-01 182259](https://github.com/Devaansh-Kumar/TalkToMe/assets/88677902/f140218a-cfce-47cb-a6b7-abe369f48c9c)

**Comment by thanhhiepvo** [comment]
I have installed the React Developer Tools. Now I am trying to fix the bug with API_KEY in firebase
